# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://developer.horse/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
gems:
   - jemoji
   - jekyll-redirect-from
future: true
timezone: Etc/UTC

# Metadata
keywords: "brony, my little pony, horse, pony devs, meetup, philadelphia, baltimore, seattle, talks, developer, panel, meetup.com"
google-fonts: "PT+Mono:400,700|PT+Sans:400,700"
google-fonts-subsets: "latin"
google-analytics: "UA-48655154-2"

# Commonly used lingo
title: "#ponydev"
email: victor@poniverse.net
description: > # this means to ignore newlines until the next colon
  Come join us!
twitter: pixelyunicorn
github: ponydevs
slack: ""
discord: "https://discord.gg/D9B6AvD"
